name: PipelineWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipeline Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/chamindaindunil/AgileProject
            azure-pipeline-name: 'webapp (1)'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
